# 3.2 Installing jamovi {.unnumbered}

To install jamovi, go to the [download page](https://www.jamovi.org/download.html).

I recommend downloading the **current** version with the latest features, but you may want to get the solid version if you prefer something more stable.

jamovi has more [documentation on how to install jamovi](https://docs.jamovi.org/_pages/um_1_installation.html) per operating system. Installation on macOS and Windows should be pretty straightforward.

A few notes:

-   Here's some guidance if you are getting an error on Windows that "[The app you're trying to install isn't a Microsoft verified app.](https://answers.microsoft.com/en-us/windows/forum/all/the-app-youre-trying-to-install-isnt-a-microsoft/5379f8e3-72e1-4cf4-8497-7983af281a05)"
-   Chromebooks can be trickier. If your Chromebook does not use Linux, you may have difficulty installing jamovi. If so, look for Chromebook-specific installation support, such as this video on [installing jamovi on a Chromebook](https://www.youtube.com/watch?v=h4ECIS57TPw).

If you are unable to install jamovi right away, do not panic. Contact the instructor or teaching assistant for support. The most important thing is to start getting familiar with the software and how it is organized.
