---
editor_options: 
  markdown: 
    wrap: 72
---

# (PART) Psychometrics {.unnumbered}

# 15. Reliability

::: {.info data-latex=""}
This chapter is a work in progress.
:::

**Reliability** is the consistency of a measure. There are three types
of consistency:

1.  *Test-retest reliability*: consistency over time (measured with a
    correlation, usually)

2.  *Internal consistency*: consistency across items (measured with
    Cronbach’s alpha usually, but there are other methods out there
    including Omega which may be more appropriate; more info provided
    soon)

3.  *Inter-rater reliability*: consistency across different researchers
    (various methods, including percent agreement, interclass or
    intraclass correlation, Cohen’s Kappa, Fleiss’ Kappa, etc.)

## Threats to Reliability

Error, which produces threats to reliability, can be introduced by:

1.  *The researcher or measurement instrument:* For example, if you’re
    measuring time to do a task, when do you start and stop the
    stopwatch? How quickly can you react to starting and stopping the
    stopwatch? What if multiple researchers are using a stopwatch?

2.  *The participant*: For instance, a participant’s mood may affect how
    they respond to a survey or the time of day may affect their weight
    on a scale (note that their weight fluctuates throughout the day but
    that affects the reliability of their weight, not the reliability of
    the scale!)

3.  *The environment*: For example, baking at different altitudes
    requires different oven temperatures and baking times.
